### PR TITLE
shell interface with __main__.py & made into a Namespace Package

### PR DESCRIPTION
**Pull request by rtruxal**
yeah so I like changed the entire layout of the package...It's now a namespace package...yeah.

### CODE REVIEW

**Comment by rtruxal** [comment]
Hey so my branch should work. I'm going to set up a mutual test-environment for us; that way we have a single & objective measure.

Also since i can't auto-merge, you must have made changes that conflict. **I'm going to let you reconcile them so i don't break anything.**

**Comment by rtruxal** [comment]
I REJECT THYNE FIX BECAUSE IT STILL MAKES USE OF THE SHELL-SCRIPT!
also I have a more comprehensive, albeit rambly elif-cascade fix in the module I added. 
Just need to test.

**Comment by N2ITN** [comment]
Can't you just call your version of `update_servers()`? Does `def  rambly_elif_cascade(): ` do something that this func doesn't? 

Welll, either way, once this PR is merged I'll look it over and tighten things up if that is okay with you. _WITH OUR POWERS COMBINED!_

**Comment by rtruxal** [comment]
lololol ur git kraken skills won't help you here. I got this.

**Comment by rtruxal** [comment]
HOLY HELL THAT WAS LAME. 
Whatever tho. It is done & working on debian. (<_>) I want die.

**Comment by rtruxal** [comment]
ok I'm struggling

**Comment by rtruxal** [comment]
FUCKIT
ima clone your branch and then delete these.

**Pull request merged**
